# Instructions: 130
# Field description:
#  |- [0] - Mnemonic
#  |- [1] - Description
#  |---- [ 0] - Operands
#  |---- [ 1] - Encoding (NONE, I, MI, MR, RM, O, M, II, RMI, D, MRI)
#  |---- [ 2] - Opcode
#  |---- [ 3] - Rex.W prefix (0x00 or 0x48)
#  |---- [ 4] - Opcode field (0..7)
#  |---- [ 5] - Opcode add (True, False)
#  |---- [ 6] - Reg (True, False)
#  |---- [ 7] - Immedicate size (0=None, 8, 16, 32, 64)
#  |---- [ 8] - Architecture (ANY, X86, X64)
#  |---- [ 9] - Lock (True, False)
#  |---- [10] - Description

OpcodeVariants = [
    [ "AAA", "ASCII Adjust After Addition.", [
        [ []                                                , "NONE", [ 0x37 ]            , 0x00, 0, False, False,  0, "X86", False, "ASCII adjust AL after addition." ],
    ]],
    [ "AAS", "ASCII Adjust AL After Subtraction.", [
        [ []                                                , "NONE", [ 0x3F ]            , 0x00, 0, False, False,  0, "X86", False, "ASCII adjust AL after subtraction." ],
    ]],
    [ "AAD", "ASCII Adjust AX Before Division", [
        [ []                                                , "NONE", [ 0xD5, 0x0A]       , 0x00, 0, False, False,  8, "X86", False, "ASCII adjust AX before division." ],
        [ ["ib"]                                            , "I"   , [ 0xD5 ]            , 0x00, 0, False, False,  8, "X86", False, "Adjust AX before division to number base imm8." ],
    ]],
    [ "AAM", "ASCII Adjust AX After Multiply", [
        [ []                                                , "NONE", [ 0xD4, 0x0A ]      , 0x00, 0, False, False,  8, "X86", False, "ASCII adjust AX after multiply." ],
        [ ["ib"]                                            , "I"   , [ 0xD4 ]            , 0x00, 0, False, False,  8, "X86", False, "Adjust AX after multiply to number base imm8." ],
    ]],
    [ "ADC", "Add with Carry", [
        [ ["al", "ib"]                                      , "I"   , [ 0x14 ]            , 0x00, 0, False, False,  8, "ANY", True , "" ],
        [ ["ax", "iw"]                                      , "I"   , [ 0x66, 0x15 ]      , 0x00, 0, False, False, 16, "ANY", True , "" ],
        [ ["eax", "id"]                                     , "I"   , [ 0x15 ]            , 0x00, 0, False, False, 32, "ANY", True , "" ],
        [ ["rax", "id"]                                     , "I"   , [ 0x15 ]            , 0x48, 0, False, False, 32, "X64", True , "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0x80 ]            , 0x00, 2, False, False,  8, "ANY", True , "" ],
        [ ["r16/m16", "iw"]                                 , "MI"  , [ 0x66, 0x81 ]      , 0x00, 2, False, False, 16, "ANY", True , "" ],
        [ ["r32/m32", "id"]                                 , "MI"  , [ 0x81 ]            , 0x00, 2, False, False, 32, "ANY", True , "" ],
        [ ["r64/m64", "id"]                                 , "MI"  , [ 0x81 ]            , 0x48, 2, False, False, 32, "X64", True , "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0x83 ]      , 0x00, 2, False, False,  8, "ANY", True , "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x00, 2, False, False,  8, "ANY", True , "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x48, 2, False, False,  8, "X64", True , "" ],
        [ ["r8/m8", "r8"]                                   , "MR"  , [ 0x10 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x11 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x11 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x11 ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
        [ ["r8", "r8/m8"]                                   , "RM"  , [ 0x12 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x13 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x13 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x13 ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
    ]],
    [ "ADD", "Add", [
        [ ["al", "ib"]                                      , "I"   , [ 0x04 ]            , 0x00, 0, False, False,  8, "ANY", True , "" ],
        [ ["ax", "iw"]                                      , "I"   , [ 0x66, 0x05 ]      , 0x00, 0, False, False, 16, "ANY", True , "" ],
        [ ["eax", "id"]                                     , "I"   , [ 0x05 ]            , 0x00, 0, False, False, 32, "ANY", True , "" ],
        [ ["rax", "id"]                                     , "I"   , [ 0x05 ]            , 0x48, 0, False, False, 32, "X64", True , "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0x80 ]            , 0x00, 0, False, False,  8, "ANY", True , "" ],
        [ ["r16/m16", "iw"]                                 , "MI"  , [ 0x66, 0x81 ]      , 0x00, 0, False, False, 16, "ANY", True , "" ],
        [ ["r32/m32", "id"]                                 , "MI"  , [ 0x81 ]            , 0x00, 0, False, False, 32, "ANY", True , "" ],
        [ ["r64/m64", "id"]                                 , "MI"  , [ 0x81 ]            , 0x48, 0, False, False, 32, "X64", True , "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0x83 ]      , 0x00, 0, False, False,  8, "ANY", True , "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x00, 0, False, False,  8, "ANY", True , "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x48, 0, False, False,  8, "X64", True , "" ],
        [ ["r8/m8", "r8"]                                   , "MR"  , [ 0x00 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x01 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x01 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x01 ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
        [ ["r8", "r8/m8"]                                   , "RM"  , [ 0x02 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x03 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x03 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x03 ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
    ]],
    [ "AND", "Logical AND", [
        [ ["al", "ib"]                                      , "I"   , [ 0x24 ]            , 0x00, 0, False, False,  8, "ANY", True , "" ],
        [ ["ax", "iw"]                                      , "I"   , [ 0x66, 0x25 ]      , 0x00, 0, False, False, 16, "ANY", True , "" ],
        [ ["eax", "id"]                                     , "I"   , [ 0x25 ]            , 0x00, 0, False, False, 32, "ANY", True , "" ],
        [ ["rax", "id"]                                     , "I"   , [ 0x25 ]            , 0x48, 0, False, False, 32, "X64", True , "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0x80 ]            , 0x00, 4, False, False,  8, "ANY", True , "" ],
        [ ["r16/m16", "iw"]                                 , "MI"  , [ 0x66, 0x81 ]      , 0x00, 4, False, False, 16, "ANY", True , "" ],
        [ ["r32/m32", "id"]                                 , "MI"  , [ 0x81 ]            , 0x00, 4, False, False, 32, "ANY", True , "" ],
        [ ["r64/m64", "id"]                                 , "MI"  , [ 0x81 ]            , 0x48, 4, False, False, 32, "X64", True , "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0x83 ]      , 0x00, 4, False, False,  8, "ANY", True , "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x00, 4, False, False,  8, "ANY", True , "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x48, 4, False, False,  8, "X64", True , "" ],
        [ ["r8/m8", "r8"]                                   , "MR"  , [ 0x20 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x21 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x21 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x21 ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
        [ ["r8", "r8/m8"]                                   , "RM"  , [ 0x22 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x23 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x23 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x23 ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
    ]],
    [ "BSF", "Bit Scan Forward", [
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x0F, 0xBC ], 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x0F, 0xBC ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x0F, 0xBC ]      , 0x48, 0, False, True ,  0, "X64", False, "" ],
    ]],
    [ "BSR", "Bit Scan Reverse", [
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x0F, 0xBD ], 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x0F, 0xBD ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x0F, 0xBD ]      , 0x48, 0, False, True ,  0, "X64", False, "" ],
    ]],
    [ "BSWAP", "Byte Swap", [
        [ ["r32"]                                           , "O"   , [ 0x0F, 0xC8 ]      , 0x00, 0, True , False,  0, "ANY", False, "" ],
        [ ["r64"]                                           , "O"   , [ 0x0F, 0xC8 ]      , 0x48, 0, True , False,  0, "X64", False, "" ],
    ]],
    [ "BT", "Bit Test", [
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x0F, 0xA3 ], 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x0F, 0xA3 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x0F, 0xA3 ]      , 0x48, 0, False, True ,  0, "X64", False, "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0x0F, 0xBA ], 0x00, 4, False, False,  8, "ANY", False, "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0x0F, 0xBA ]      , 0x00, 4, False, False,  8, "ANY", False, "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0x0F, 0xBA ]      , 0x48, 4, False, False,  8, "X64", False, "" ],
    ]],
    [ "BTC", "Bit Test and Complement", [
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x0F, 0xBB ], 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x0F, 0xBB ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x0F, 0xBB ]      , 0x48, 0, False, True ,  0, "X64", True , "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0x0F, 0xBA ], 0x00, 7, False, False,  8, "ANY", True , "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0x0F, 0xBA ]      , 0x00, 7, False, False,  8, "ANY", True , "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0x0F, 0xBA ]      , 0x48, 7, False, False,  8, "X64", True , "" ],
    ]],
    [ "BTR", "Bit Test and Reset.", [
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x0F, 0xB3 ], 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x0F, 0xB3 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x0F, 0xB3 ]      , 0x48, 0, False, True ,  0, "X64", True , "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0x0F, 0xBA ], 0x00, 6, False, False,  8, "ANY", True , "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0x0F, 0xBA ]      , 0x00, 6, False, False,  8, "ANY", True , "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0x0F, 0xBA ]      , 0x48, 6, False, False,  8, "X64", True , "" ],
    ]],
    [ "BTS", "Bit Test and Set", [
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x0F, 0xAB ], 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x0F, 0xAB ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x0F, 0xAB ]      , 0x48, 0, False, True ,  0, "X64", True , "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0x0F, 0xBA ], 0x00, 5, False, False,  8, "ANY", True , "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0x0F, 0xBA ]      , 0x00, 5, False, False,  8, "ANY", True , "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0x0F, 0xBA ]      , 0x48, 5, False, False,  8, "X64", True , "" ],
    ]],
    [ "CALL", "Call Procedure", [
        [ ["rel32"]                                         , "M"   , [ 0xE8, 0xcd ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["rxx/mxx"]                                       , "M"   , [ 0xFF ]            , 0x00, 2, False, False,  0, "ANY", False, "" ],
    ]],
    [ "CBW", "", [
        [ []                                                , "NONE", [ 0x66, 0x98 ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "CWDE", "", [
        [ ["<eax>"]                                         , "NONE", [ 0x98 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "CDQE", "", [
        [ ["<rax>"]                                         , "NONE", [ 0x98 ]            , 0x48, 0, False, False,  0, "X64", False, "" ],
    ]],
    [ "CWD", "", [
        [ ["<dx>", "<ax>"]                                  , "NONE", [ 0x66, 0x99 ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "CDQ", "", [
        [ ["<edx>", "<eax>"]                                , "NONE", [ 0x99 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "CQO", "", [
        [ ["<rdx>", "<rax>"]                                , "NONE", [ 0x99 ]            , 0x48, 0, False, False,  0, "X64", False, "" ],
    ]],
    [ "CLAC", "Clear AC Flag in EFLAGS Register", [
        [ []                                                , "NONE", [ 0x0F, 0x01, 0xCA ], 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "CLC", "Clear Carry Flag", [
        [ []                                                , "NONE", [ 0xF8 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "CLD", "Clear Direction Flag", [
        [ []                                                , "NONE", [ 0xFC ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "CMC", "Complement Carry Flag", [
        [ []                                                , "NONE", [ 0xF5 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "CMOVO", "", [
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x0F, 0x40 ], 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x0F, 0x40 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x0F, 0x40 ]      , 0x48, 0, False, True ,  0, "X64", False, "" ],
    ]],
    [ "CMOVNO", "", [
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x0F, 0x41 ], 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x0F, 0x41 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x0F, 0x41 ]      , 0x48, 0, False, True ,  0, "X64", False, "" ],
    ]],
    [ "CMOVS", "", [
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x0F, 0x48 ], 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x0F, 0x48 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x0F, 0x48 ]      , 0x48, 0, False, True ,  0, "X64", False, "" ],
    ]],
    [ "CMOVNS", "", [
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x0F, 0x49 ], 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x0F, 0x49 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x0F, 0x49 ]      , 0x48, 0, False, True ,  0, "X64", False, "" ],
    ]],
    [ "CMP", "Compare Two Operands", [
        [ ["al", "ib"]                                      , "I"   , [ 0x3C ]            , 0x00, 0, False, False,  8, "ANY", False, "" ],
        [ ["ax", "iw"]                                      , "I"   , [ 0x66, 0x3D ]      , 0x00, 0, False, False, 16, "ANY", False, "" ],
        [ ["eax", "id"]                                     , "I"   , [ 0x3D ]            , 0x00, 0, False, False, 32, "ANY", False, "" ],
        [ ["rax", "id"]                                     , "I"   , [ 0x3D ]            , 0x48, 0, False, False, 32, "X64", False, "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0x80 ]            , 0x00, 7, False, False,  8, "ANY", False, "" ],
        [ ["r16/m16", "iw"]                                 , "MI"  , [ 0x66, 0x81 ]      , 0x00, 7, False, False, 16, "ANY", False, "" ],
        [ ["r32/m32", "id"]                                 , "MI"  , [ 0x81 ]            , 0x00, 7, False, False, 32, "ANY", False, "" ],
        [ ["r64/m64", "id"]                                 , "MI"  , [ 0x81 ]            , 0x48, 7, False, False, 32, "X64", False, "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0x83 ]      , 0x00, 7, False, False,  8, "ANY", False, "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x00, 7, False, False,  8, "ANY", False, "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x48, 7, False, False,  8, "X64", False, "" ],
        [ ["r8/m8", "r8"]                                   , "MR"  , [ 0x38 ]            , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x39 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x39 ]            , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x39 ]            , 0x48, 0, False, True ,  0, "X64", False, "" ],
        [ ["r8", "r8/m8"]                                   , "RM"  , [ 0x3A ]            , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x3B ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x3B ]            , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x3B ]            , 0x48, 0, False, True ,  0, "X64", False, "" ],
    ]],
    [ "CMPSB", "", [
        [ ["<ds:zsi>", "<es:zdi>"]                          , "NONE", [ 0xA6 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "CMPSW", "", [
        [ ["<ds:zsi>", "<es:zdi>"]                          , "NONE", [ 0x66, 0xA7 ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "CMPSD", "Compare Scalar Double-Precision Floating-Point Values", [
        [ ["<ds:zsi>", "<es:zdi>"]                          , "NONE", [ 0xA7 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "CMPSQ", "", [
        [ ["<ds:zsi>", "<es:zdi>"]                          , "NONE", [ 0xA7 ]            , 0x48, 0, False, False,  0, "X64", False, "" ],
    ]],
    [ "CMPXCHG", "Compare and Exchange.", [
        [ ["r8/m8", "r8", "<al>"]                           , "MR"  , [ 0x0F, 0xB0 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16/m16", "r16", "<ax>"]                        , "MR"  , [ 0x66, 0x0F, 0xB1 ], 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32/m32", "r32", "<eax>"]                       , "MR"  , [ 0x0F, 0xB1 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64/m64", "r64", "<rax>"]                       , "MR"  , [ 0x0F, 0xB1 ]      , 0x48, 0, False, True ,  0, "X64", True , "" ],
    ]],
    [ "CMPXCHG8B", "", [
        [ ["m64", "<edx>", "<eax>", "<ecx>", "<ebx>"]       , "M"   , [ 0x0F, 0xC7 ]      , 0x00, 1, False, False,  0, "ANY", True , "" ],
    ]],
    [ "CMPXCHG16B", "", [
        [ ["m128", "<rdx>", "<rax>", "<rcx>", "<rbx>"]      , "M"   , [ 0x0F, 0xC7 ]      , 0x48, 1, False, False,  0, "X64", True , "" ],
    ]],
    [ "CPUID", "CPU Identification.", [
        [ []                                                , "NONE", [ 0x0F, 0xA2 ]      , 0x00, 0, False, False,  0, "ANY", False, "Returns processor identification and feature information to the EAX, EBX, ECX, and EDX registers, as determined by input entered in EAX (in some cases, ECX as well)"],
    ]],
    [ "DAA", "Decimal Adjust AL after Addition", [
        [ ["<ax>"]                                          , "NONE", [ 0x27 ]            , 0x00, 0, False, False,  0, "X86", False, "" ],
    ]],
    [ "DAS", "Decimal Adjust AL after Subtraction", [
        [ ["<ax>"]                                          , "NONE", [ 0x2F ]            , 0x00, 0, False, False,  0, "X86", False, "" ],
    ]],
    [ "DEC", "Decrement by 1.", [
        [ ["r16"]                                           , "O"   , [ 0x66, 0x48 ]      , 0x00, 0, True , False,  0, "X86", True , "" ],
        [ ["r32"]                                           , "O"   , [ 0x48 ]            , 0x00, 0, True , False,  0, "X86", True , "" ],
        [ ["r8/m8"]                                         , "M"   , [ 0xFE ]            , 0x00, 1, False, False,  0, "ANY", True , "" ],
        [ ["r16/m16"]                                       , "M"   , [ 0x66, 0xFF ]      , 0x00, 1, False, False,  0, "ANY", True , "" ],
        [ ["r32/m32"]                                       , "M"   , [ 0xFF ]            , 0x00, 1, False, False,  0, "ANY", True , "" ],
        [ ["r64/m64"]                                       , "M"   , [ 0xFF ]            , 0x48, 1, False, False,  0, "X64", True , "" ],
    ]],
    [ "DIV", "Unsigned Divide", [
        [ ["<ax>", "r8/m8"]                                 , "M"   , [ 0xF6 ]            , 0x00, 6, False, False,  0, "ANY", False, "" ],
        [ ["<ax>", "<dx>", "r16/m16"]                       , "M"   , [ 0x66, 0xF7 ]      , 0x00, 6, False, False,  0, "ANY", False, "" ],
        [ ["<eax>", "<edx>", "r32/m32"]                     , "M"   , [ 0xF7 ]            , 0x00, 6, False, False,  0, "ANY", False, "" ],
        [ ["<rax>", "<rdx>", "r64/m64"]                     , "M"   , [ 0xF7 ]            , 0x48, 6, False, False,  0, "X64", False, "" ],
    ]],
    [ "ENTER", "Make Stack Frame for Procedure Parameters", [
        [ ["iw", "ib"]                                      , "II"  , [ 0xC8 ]            , 0x00, 0, False, False,  8, "ANY", False, "" ],
    ]],
    [ "IDIV", "Signed Divide.", [
        [ ["<ax>", "r8/m8"]                                 , "M"   , [ 0xF6 ]            , 0x00, 7, False, False,  0, "ANY", False, "" ],
        [ ["<dx>", "<ax>", "r16/m16"]                       , "M"   , [ 0x66, 0xF7 ]      , 0x00, 7, False, False,  0, "ANY", False, "" ],
        [ ["<edx>", "<eax>", "r32/m32"]                     , "M"   , [ 0xF7 ]            , 0x00, 7, False, False,  0, "ANY", False, "" ],
        [ ["<rdx>", "<rax>", "r64/m64"]                     , "M"   , [ 0xF7 ]            , 0x48, 7, False, False,  0, "X64", False, "" ],
    ]],
    [ "IMUL", "Signed Multiply", [
        [ ["<ax>", "r8/m8"]                                 , "M"   , [ 0xF6 ]            , 0x00, 5, False, False,  0, "ANY", False, "" ],
        [ ["<dx>", "<ax>", "r16/m16"]                       , "M"   , [ 0x66, 0xF7 ]      , 0x00, 5, False, False,  0, "ANY", False, "" ],
        [ ["<edx>", "<eax>", "r32/m32"]                     , "M"   , [ 0xF7 ]            , 0x00, 5, False, False,  0, "ANY", False, "" ],
        [ ["<rdx>", "<rax>", "r64/m64"]                     , "M"   , [ 0xF7 ]            , 0x48, 5, False, False,  0, "X64", False, "" ],
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x0F, 0xAF ], 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x0F, 0xAF ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x0F, 0xAF ]      , 0x48, 0, False, True ,  0, "X64", False, "" ],
        [ ["r16", "r16/m16", "ib"]                          , "RMI" , [ 0x66, 0x6B ]      , 0x00, 0, False, True ,  8, "ANY", False, "" ],
        [ ["r32", "r32/m32", "ib"]                          , "RMI" , [ 0x6B ]            , 0x00, 0, False, True ,  8, "ANY", False, "" ],
        [ ["r64", "r64/m64", "ib"]                          , "RMI" , [ 0x6B ]            , 0x48, 0, False, True ,  8, "X64", False, "" ],
        [ ["r16", "r16/m16", "iw"]                          , "RMI" , [ 0x66, 0x69 ]      , 0x00, 0, False, True , 16, "ANY", False, "" ],
        [ ["r32", "r32/m32", "id"]                          , "RMI" , [ 0x69 ]            , 0x00, 0, False, True , 32, "ANY", False, "" ],
        [ ["r64", "r64/m64", "id"]                          , "RMI" , [ 0x69 ]            , 0x48, 0, False, True , 32, "X64", False, "" ],
    ]],
    [ "INC", "Increment by", [
        [ ["r16"]                                           , "O"   , [ 0x66, 0x40 ]      , 0x00, 0, True , False,  0, "X86", True , "" ],
        [ ["r32"]                                           , "O"   , [ 0x40 ]            , 0x00, 0, True , False,  0, "X86", True , "" ],
        [ ["r8/m8"]                                         , "M"   , [ 0xFE ]            , 0x00, 0, False, False,  0, "ANY", True , "" ],
        [ ["r16/m16"]                                       , "M"   , [ 0x66, 0xFF ]      , 0x00, 0, False, False,  0, "ANY", True , "" ],
        [ ["r32/m32"]                                       , "M"   , [ 0xFF ]            , 0x00, 0, False, False,  0, "ANY", True , "" ],
        [ ["r64/m64"]                                       , "M"   , [ 0xFF ]            , 0x48, 0, False, False,  0, "X64", True , "" ],
    ]],
    [ "IN", "Input from Port", [
        [ ["al", "ib"]                                      , "I"   , [ 0xE4 ]            , 0x00, 0, False, False,  8, "ANY", False, "" ],
        [ ["ax", "ib"]                                      , "I"   , [ 0x66, 0xE5 ]      , 0x00, 0, False, False,  8, "ANY", False, "" ],
        [ ["eax", "ib"]                                     , "I"   , [ 0xE5 ]            , 0x00, 0, False, False,  8, "ANY", False, "" ],
        [ ["al", "dx"]                                      , "NONE", [ 0xEC ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["ax", "dx"]                                      , "NONE", [ 0x66, 0xED ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["eax", "dx"]                                     , "NONE", [ 0xED ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "INSB", "", [
        [ ["es:zdi", "dx"]                                  , "NONE", [ 0x6C ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "INSW", "", [
        [ ["es:zdi", "dx"]                                  , "NONE", [ 0x66, 0x6D ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "INSD", "", [
        [ ["es:zdi", "dx"]                                  , "NONE", [ 0x6D ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "INT", "", [
        [ ["ib"]                                            , "I"   , [ 0xCD ]            , 0x00, 0, False, False,  8, "ANY", False, "" ],
    ]],
    [ "INT3", "", [
        [ []                                                , "NONE", [ 0xCC ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "INTO", "", [
        [ []                                                , "NONE", [ 0xCE ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "JO", "", [
        [ ["rel8"]                                          , "D"   , [ 0x70, 0xcb ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["rel32"]                                         , "D"   , [ 0x0F, 0x80, 0xcd ], 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "JNO", "", [
        [ ["rel8"]                                          , "D"   , [ 0x71, 0xcb ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["rel32"]                                         , "D"   , [ 0x0F, 0x81, 0xcd ], 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "JS", "", [
        [ ["rel8"]                                          , "D"   , [ 0x78, 0xcb ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["rel32"]                                         , "D"   , [ 0x0F, 0x88, 0xcd ], 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "JNS", "", [
        [ ["rel8"]                                          , "D"   , [ 0x79, 0xcb ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["rel32"]                                         , "D"   , [ 0x0F, 0x89, 0xcd ], 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "JCXZ", "", [
        [ ["cx", "rel8"]                                    , "D"   , [ 0x67, 0xE3, 0xcb ], 0x00, 0, False, False,  0, "X86", False, "" ],
    ]],
    [ "JECXZ", "", [
        [ ["ecx", "rel8"]                                   , "D"   , [ 0xE3, 0xcb ]      , 0x00, 0, False, False,  0, "X86", False, "" ],
        [ ["ecx", "rel8"]                                   , "D"   , [ 0x67, 0xE3, 0xcb ], 0x00, 0, False, False,  0, "X64", False, "" ],
    ]],
    [ "JRCXZ", "", [
        [ ["rcx", "rel8"]                                   , "D"   , [ 0xE3, 0xcb ]      , 0x00, 0, False, False,  0, "X64", False, "" ],
    ]],
    [ "JZCXZ", "", [
        [ ["zcx", "rel8"]                                   , "D"   , [ 0xE3, 0xcb ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "JMP", "Jump", [
        [ ["rel8"]                                          , "D"   , [ 0xEB, 0xcb ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["rel32"]                                         , "D"   , [ 0xE9, 0xcd ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["rxx/mxx"]                                       , "D"   , [ 0xFF ]            , 0x00, 4, False, False,  0, "ANY", False, "" ],
    ]],
    [ "LAHF", "Load Status Flags into AH Register", [
        [ ["<ah>"]                                          , "NONE", [ 0x9F ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "LEA", "Load Effective Address", [
        [ ["r16", "mem"]                                    , "RM"  , [ 0x67, 0x8D ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32", "mem"]                                    , "RM"  , [ 0x8D ]            , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64", "mem"]                                    , "RM"  , [ 0x8D ]            , 0x48, 0, False, True ,  0, "X64", False, "" ],
    ]],
    [ "LEAVE", "High Level Procedure Exit", [
        [ []                                                , "NONE", [ 0xC9 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "LODSB", "", [
        [ ["<al>", "<ds:zsi>"]                              , "NONE", [ 0xAC ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "LODSW", "", [
        [ ["<ax>", "<ds:zsi>"]                              , "NONE", [ 0x66, 0xAD ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "LODSD", "", [
        [ ["<eax>", "<ds:zsi>"]                             , "NONE", [ 0xAD ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "LODSQ", "", [
        [ ["<rax>", "<ds:zsi>"]                             , "NONE", [ 0xAD ]            , 0x48, 0, False, False,  0, "X64", False, "" ],
    ]],
    [ "LOOP", "", [
        [ ["cx", "rel8"]                                    , "D"   , [ 0x67, 0xE2, 0xcb ], 0x00, 0, False, False,  0, "X86", False, "" ],
        [ ["ecx", "rel8"]                                   , "D"   , [ 0xE2, 0xcb ]      , 0x00, 0, False, False,  0, "X86", False, "" ],
        [ ["ecx", "rel8"]                                   , "D"   , [ 0x67, 0xE2, 0xcb ], 0x00, 0, False, False,  0, "X64", False, "" ],
        [ ["rcx", "rel8"]                                   , "D"   , [ 0xE2, 0xcb ]      , 0x00, 0, False, False,  0, "X64", False, "" ],
    ]],
    [ "LOOPE", "", [
        [ ["cx", "rel8"]                                    , "D"   , [ 0x67, 0xE1, 0xcb ], 0x00, 0, False, False,  0, "X86", False, "" ],
        [ ["ecx", "rel8"]                                   , "D"   , [ 0xE1, 0xcb ]      , 0x00, 0, False, False,  0, "X86", False, "" ],
        [ ["ecx", "rel8"]                                   , "D"   , [ 0x67, 0xE1, 0xcb ], 0x00, 0, False, False,  0, "X64", False, "" ],
        [ ["rcx", "rel8"]                                   , "D"   , [ 0xE1, 0xcb ]      , 0x00, 0, False, False,  0, "X64", False, "" ],
    ]],
    [ "LOOPNE", "", [
        [ ["cx", "rel8"]                                    , "D"   , [ 0x67, 0xE0, 0xcb ], 0x00, 0, False, False,  0, "X86", False, "" ],
        [ ["ecx", "rel8"]                                   , "D"   , [ 0xE0, 0xcb ]      , 0x00, 0, False, False,  0, "X86", False, "" ],
        [ ["ecx", "rel8"]                                   , "D"   , [ 0x67, 0xE0, 0xcb ], 0x00, 0, False, False,  0, "X64", False, "" ],
        [ ["rcx", "rel8"]                                   , "D"   , [ 0xE0, 0xcb ]      , 0x00, 0, False, False,  0, "X64", False, "" ],
    ]],
    [ "MOV", "Move", [
        [ ["r8/m8", "r8"]                                   , "MR"  , [ 0x88 ]            , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x89 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x89 ]            , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x89 ]            , 0x48, 0, False, True ,  0, "X64", False, "" ],
        [ ["r8", "r8/m8"]                                   , "RM"  , [ 0x8A ]            , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x8B ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x8B ]            , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x8B ]            , 0x48, 0, False, True ,  0, "X64", False, "" ],
        [ ["r16/m16", "sreg"]                               , "MR"  , [ 0x8C ]            , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64/m64", "sreg"]                               , "MR"  , [ 0x8C ]            , 0x48, 0, False, True ,  0, "X64", False, "" ],
        [ ["sreg", "r16/m16"]                               , "RM"  , [ 0x8E ]            , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["sreg", "r64/m64"]                               , "RM"  , [ 0x8E ]            , 0x48, 0, False, True ,  0, "X64", False, "" ],
        [ ["al", "moff8"]                                   , "NONE", [ 0xA0 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["ax", "moff16"]                                  , "NONE", [ 0x66, 0xA1 ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["eax", "moff32"]                                 , "NONE", [ 0xA1 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["rax", "moff64"]                                 , "NONE", [ 0xA1 ]            , 0x48, 0, False, False,  0, "X64", False, "" ],
        [ ["moff8", "al"]                                   , "NONE", [ 0xA2 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["moff16", "ax"]                                  , "NONE", [ 0x66, 0xA3 ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["moff32", "eax"]                                 , "NONE", [ 0xA3 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["moff64", "rax"]                                 , "NONE", [ 0xA3 ]            , 0x48, 0, False, False,  0, "X64", False, "" ],
        [ ["r8", "ib"]                                      , "I"   , [ 0xB0 ]            , 0x00, 0, True , False,  8, "ANY", False, "" ],
        [ ["r16", "iw"]                                     , "I"   , [ 0x66, 0xB8 ]      , 0x00, 0, True , False, 16, "ANY", False, "" ],
        [ ["r32", "id"]                                     , "I"   , [ 0xB8 ]            , 0x00, 0, True , False, 32, "ANY", False, "" ],
        [ ["r64", "iq"]                                     , "I"   , [ 0xB8 ]            , 0x48, 0, True , False, 64, "X64", False, "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0xC6 ]            , 0x00, 0, False, False,  8, "ANY", False, "" ],
        [ ["r16/m16", "iw"]                                 , "MI"  , [ 0x66, 0xC7 ]      , 0x00, 0, False, False, 16, "ANY", False, "" ],
        [ ["r32/m32", "id"]                                 , "MI"  , [ 0xC7 ]            , 0x00, 0, False, False, 32, "ANY", False, "" ],
        [ ["r64/m64", "id"]                                 , "MI"  , [ 0xC7 ]            , 0x48, 0, False, False, 32, "X64", False, "" ],
        [ ["rxx", "creg"]                                   , "MR"  , [ 0x0F, 0x20 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["creg", "rxx"]                                   , "RM"  , [ 0x0F, 0x22 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["rxx", "dreg"]                                   , "MR"  , [ 0x0F, 0x21 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["dreg", "rxx"]                                   , "RM"  , [ 0x0F, 0x23 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
    ]],
    [ "MOVSB", "", [
        [ ["<es:zdi>", "<ds:zsi>"]                          , "NONE", [ 0xA4 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "MOVSW", "", [
        [ ["<es:zdi>", "<ds:zsi>"]                          , "NONE", [ 0x66, 0xA5 ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "MOVSD", "Move Scalar Double-Precision Floating-Point Value", [
        [ ["<es:zdi>", "<ds:zsi>"]                          , "NONE", [ 0xA5 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "MOVSQ", "", [
        [ ["<es:zdi>", "<ds:zsi>"]                          , "NONE", [ 0xA5 ]            , 0x48, 0, False, False,  0, "X64", False, "" ],
    ]],
    [ "MOVSX", "", [
        [ ["r16", "r8/m8"]                                  , "RM"  , [ 0x66, 0x0F, 0xBE ], 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32", "r8/m8"]                                  , "RM"  , [ 0x0F, 0xBE ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64", "r8/m8"]                                  , "RM"  , [ 0x0F, 0xBE ]      , 0x48, 0, False, True ,  0, "X64", False, "" ],
        [ ["r32", "r16/m16"]                                , "RM"  , [ 0x0F, 0xBF ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64", "r16/m16"]                                , "RM"  , [ 0x0F, 0xBF ]      , 0x48, 0, False, True ,  0, "X64", False, "" ],
    ]],
    [ "MOVSXD", "", [
        [ ["r64", "r32/m32"]                                , "RM"  , [ 0x63 ]            , 0x48, 0, False, True ,  0, "X64", False, "" ],
    ]],
    [ "MOVZX", "Move with Zero-Extend.", [
        [ ["r16", "r8/m8"]                                  , "RM"  , [ 0x66, 0x0F, 0xB6 ], 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32", "r8/m8"]                                  , "RM"  , [ 0x0F, 0xB6 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64", "r8/m8"]                                  , "RM"  , [ 0x0F, 0xB6 ]      , 0x48, 0, False, True ,  0, "X64", False, "" ],
        [ ["r32", "r16/m16"]                                , "RM"  , [ 0x0F, 0xB7 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64", "r16/m16"]                                , "RM"  , [ 0x0F, 0xB7 ]      , 0x48, 0, False, True ,  0, "X64", False, "" ],
    ]],
    [ "MUL", "Unsigned Multiply.", [
        [ ["<ax>", "r8/m8"]                                 , "M"   , [ 0xF6 ]            , 0x00, 4, False, False,  0, "ANY", False, "" ],
        [ ["<dx>", "<ax>", "r16/m16"]                       , "M"   , [ 0x66, 0xF7 ]      , 0x00, 4, False, False,  0, "ANY", False, "" ],
        [ ["<edx>", "<eax>", "r32/m32"]                     , "M"   , [ 0xF7 ]            , 0x00, 4, False, False,  0, "ANY", False, "" ],
        [ ["<rdx>", "<rax>", "r64/m64"]                     , "M"   , [ 0xF7 ]            , 0x48, 4, False, False,  0, "X64", False, "" ],
    ]],
    [ "NEG", "Two's Complement Negation", [
        [ ["r8/m8"]                                         , "M"   , [ 0xF6 ]            , 0x00, 3, False, False,  0, "ANY", False, "" ],
        [ ["r16/m16"]                                       , "M"   , [ 0x66, 0xF7 ]      , 0x00, 3, False, False,  0, "ANY", False, "" ],
        [ ["r32/m32"]                                       , "M"   , [ 0xF7 ]            , 0x00, 3, False, False,  0, "ANY", False, "" ],
        [ ["r64/m64"]                                       , "M"   , [ 0xF7 ]            , 0x48, 3, False, False,  0, "X64", False, "" ],
    ]],
    [ "NOP", "No Operation.", [
        [ []                                                , "NONE", [ 0x90 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["r16/m16"]                                       , "M"   , [ 0x66, 0x0F, 0x1F ], 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["r32/m32"]                                       , "M"   , [ 0x0F, 0x1F ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "NOT", "One's Complement Negation", [
        [ ["r8/m8"]                                         , "M"   , [ 0xF6 ]            , 0x00, 2, False, False,  0, "ANY", False, "" ],
        [ ["r16/m16"]                                       , "M"   , [ 0x66, 0xF7 ]      , 0x00, 2, False, False,  0, "ANY", False, "" ],
        [ ["r32/m32"]                                       , "M"   , [ 0xF7 ]            , 0x00, 2, False, False,  0, "ANY", False, "" ],
        [ ["r64/m64"]                                       , "M"   , [ 0xF7 ]            , 0x48, 2, False, False,  0, "X64", False, "" ],
    ]],
    [ "OR", "Logical Inclusive OR", [
        [ ["al", "ib"]                                      , "I"   , [ 0x0C ]            , 0x00, 0, False, False,  8, "ANY", True , "" ],
        [ ["ax", "iw"]                                      , "I"   , [ 0x66, 0x0D ]      , 0x00, 0, False, False, 16, "ANY", True , "" ],
        [ ["eax", "id"]                                     , "I"   , [ 0x0D ]            , 0x00, 0, False, False, 32, "ANY", True , "" ],
        [ ["rax", "id"]                                     , "I"   , [ 0x0D ]            , 0x48, 0, False, False, 32, "X64", True , "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0x80 ]            , 0x00, 1, False, False,  8, "ANY", True , "" ],
        [ ["r16/m16", "iw"]                                 , "MI"  , [ 0x66, 0x81 ]      , 0x00, 1, False, False, 16, "ANY", True , "" ],
        [ ["r32/m32", "id"]                                 , "MI"  , [ 0x81 ]            , 0x00, 1, False, False, 32, "ANY", True , "" ],
        [ ["r64/m64", "id"]                                 , "MI"  , [ 0x81 ]            , 0x48, 1, False, False, 32, "X64", True , "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0x83 ]      , 0x00, 1, False, False,  8, "ANY", True , "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x00, 1, False, False,  8, "ANY", True , "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x48, 1, False, False,  8, "X64", True , "" ],
        [ ["r8/m8", "r8"]                                   , "MR"  , [ 0x08 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x09 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x09 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x09 ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
        [ ["r8", "r8/m8"]                                   , "RM"  , [ 0x0A ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x0B ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x0B ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x0B ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
    ]],
    [ "OUT", "Output to Port", [
        [ ["ib", "al"]                                      , "I"   , [ 0xE6 ]            , 0x00, 0, False, False,  8, "ANY", False, "" ],
        [ ["ib", "ax"]                                      , "I"   , [ 0x66, 0xE7 ]      , 0x00, 0, False, False,  8, "ANY", False, "" ],
        [ ["ib", "eax"]                                     , "I"   , [ 0xE7 ]            , 0x00, 0, False, False,  8, "ANY", False, "" ],
        [ ["dx", "al"]                                      , "NONE", [ 0xEE ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["dx", "ax"]                                      , "NONE", [ 0x66, 0xEF ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["dx", "eax"]                                     , "NONE", [ 0xEF ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "OUTSB", "", [
        [ ["dx", "ds:zsi"]                                  , "NONE", [ 0x6E ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "OUTSW", "", [
        [ ["dx", "ds:zsi"]                                  , "NONE", [ 0x66, 0x6F ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "OUTSD", "", [
        [ ["dx", "ds:zsi"]                                  , "NONE", [ 0x6F ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "PAUSE", "Spin Loop Hint", [
        [ []                                                , "NONE", [ 0xF3, 0x90 ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "POP", "Pop a Value from the Stack.", [
        [ ["r16/m16"]                                       , "M"   , [ 0x66, 0x8F ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["rxx/mxx"]                                       , "M"   , [ 0x8F ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["r16"]                                           , "O"   , [ 0x66, 0x58 ]      , 0x00, 0, True , False,  0, "ANY", False, "" ],
        [ ["rxx"]                                           , "O"   , [ 0x58 ]            , 0x00, 0, True , False,  0, "ANY", False, "" ],
        [ ["ds"]                                            , "NONE", [ 0x1F ]            , 0x00, 0, False, False,  0, "X86", False, "" ],
        [ ["es"]                                            , "NONE", [ 0x07 ]            , 0x00, 0, False, False,  0, "X86", False, "" ],
        [ ["ss"]                                            , "NONE", [ 0x17 ]            , 0x00, 0, False, False,  0, "X86", False, "" ],
        [ ["fs"]                                            , "NONE", [ 0x0F, 0xA1 ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["gs"]                                            , "NONE", [ 0x0F, 0xA9 ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "POPA", "", [
        [ []                                                , "NONE", [ 0x61 ]            , 0x00, 0, False, False,  0, "X86", False, "" ],
    ]],
    [ "POPF", "", [
        [ []                                                , "NONE", [ 0x9D ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "PUSH", "Push Word, Doubleword or Quadword Onto the Stack", [
        [ ["r16/m16"]                                       , "M"   , [ 0x66, 0xFF ]      , 0x00, 6, False, False,  0, "ANY", False, "" ],
        [ ["rxx/mxx"]                                       , "M"   , [ 0xFF ]            , 0x00, 6, False, False,  0, "ANY", False, "" ],
        [ ["r16"]                                           , "O"   , [ 0x66, 0x50 ]      , 0x00, 0, True , False,  0, "ANY", False, "" ],
        [ ["rxx"]                                           , "O"   , [ 0x50 ]            , 0x00, 0, True , False,  0, "ANY", False, "" ],
        [ ["ib"]                                            , "I"   , [ 0x6A ]            , 0x00, 0, False, False,  8, "ANY", False, "" ],
        [ ["iw"]                                            , "I"   , [ 0x66, 0x68 ]      , 0x00, 0, False, False, 16, "ANY", False, "" ],
        [ ["id"]                                            , "I"   , [ 0x68 ]            , 0x00, 0, False, False, 32, "ANY", False, "" ],
        [ ["cs"]                                            , "NONE", [ 0x0E ]            , 0x00, 0, False, False,  0, "X86", False, "" ],
        [ ["ss"]                                            , "NONE", [ 0x16 ]            , 0x00, 0, False, False,  0, "X86", False, "" ],
        [ ["ds"]                                            , "NONE", [ 0x1E ]            , 0x00, 0, False, False,  0, "X86", False, "" ],
        [ ["es"]                                            , "NONE", [ 0x06 ]            , 0x00, 0, False, False,  0, "X86", False, "" ],
        [ ["fs"]                                            , "NONE", [ 0x0F, 0xA0 ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["gs"]                                            , "NONE", [ 0x0F, 0xA8 ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "PUSHA", "", [
        [ []                                                , "NONE", [ 0x60 ]            , 0x00, 0, False, False,  0, "X86", False, "" ],
    ]],
    [ "PUSHF", "", [
        [ []                                                , "NONE", [ 0x9C ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "RCL", "", [
        [ ["r8/m8", "1"]                                    , "M"   , [ 0xD0 ]            , 0x00, 2, False, False,  0, "ANY", False, "" ],
        [ ["r8/m8", "cl"]                                   , "M"   , [ 0xD2 ]            , 0x00, 2, False, False,  0, "ANY", False, "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0xC0 ]            , 0x00, 2, False, False,  8, "ANY", False, "" ],
        [ ["r16/m16", "1"]                                  , "M"   , [ 0x66, 0xD1 ]      , 0x00, 2, False, False,  0, "ANY", False, "" ],
        [ ["r16/m16", "cl"]                                 , "M"   , [ 0x66, 0xD3 ]      , 0x00, 2, False, False,  0, "ANY", False, "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0xC1 ]      , 0x00, 2, False, False,  8, "ANY", False, "" ],
        [ ["r32/m32", "1"]                                  , "M"   , [ 0xD1 ]            , 0x00, 2, False, False,  0, "ANY", False, "" ],
        [ ["r32/m32", "cl"]                                 , "M"   , [ 0xD3 ]            , 0x00, 2, False, False,  0, "ANY", False, "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0xC1 ]            , 0x00, 2, False, False,  8, "ANY", False, "" ],
        [ ["r64/m64", "1"]                                  , "M"   , [ 0xD1 ]            , 0x48, 2, False, False,  0, "X64", False, "" ],
        [ ["r64/m64", "cl"]                                 , "M"   , [ 0xD3 ]            , 0x48, 2, False, False,  0, "X64", False, "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0xC1 ]            , 0x48, 2, False, False,  8, "X64", False, "" ],
    ]],
    [ "RCR", "", [
        [ ["r8/m8", "1"]                                    , "M"   , [ 0xD0 ]            , 0x00, 3, False, False,  0, "ANY", False, "" ],
        [ ["r8/m8", "cl"]                                   , "M"   , [ 0xD2 ]            , 0x00, 3, False, False,  0, "ANY", False, "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0xC0 ]            , 0x00, 3, False, False,  8, "ANY", False, "" ],
        [ ["r16/m16", "1"]                                  , "M"   , [ 0x66, 0xD1 ]      , 0x00, 3, False, False,  0, "ANY", False, "" ],
        [ ["r16/m16", "cl"]                                 , "M"   , [ 0x66, 0xD3 ]      , 0x00, 3, False, False,  0, "ANY", False, "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0xC1 ]      , 0x00, 3, False, False,  8, "ANY", False, "" ],
        [ ["r32/m32", "1"]                                  , "M"   , [ 0xD1 ]            , 0x00, 3, False, False,  0, "ANY", False, "" ],
        [ ["r32/m32", "cl"]                                 , "M"   , [ 0xD3 ]            , 0x00, 3, False, False,  0, "ANY", False, "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0xC1 ]            , 0x00, 3, False, False,  8, "ANY", False, "" ],
        [ ["r64/m64", "1"]                                  , "M"   , [ 0xD1 ]            , 0x48, 3, False, False,  0, "X64", False, "" ],
        [ ["r64/m64", "cl"]                                 , "M"   , [ 0xD3 ]            , 0x48, 3, False, False,  0, "X64", False, "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0xC1 ]            , 0x48, 3, False, False,  8, "X64", False, "" ],
    ]],
    [ "ROL", "", [
        [ ["r8/m8", "1"]                                    , "M"   , [ 0xD0 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["r8/m8", "cl"]                                   , "M"   , [ 0xD2 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0xC0 ]            , 0x00, 0, False, False,  8, "ANY", False, "" ],
        [ ["r16/m16", "1"]                                  , "M"   , [ 0x66, 0xD1 ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["r16/m16", "cl"]                                 , "M"   , [ 0x66, 0xD3 ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0xC1 ]      , 0x00, 0, False, False,  8, "ANY", False, "" ],
        [ ["r32/m32", "1"]                                  , "M"   , [ 0xD1 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["r32/m32", "cl"]                                 , "M"   , [ 0xD3 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0xC1 ]            , 0x00, 0, False, False,  8, "ANY", False, "" ],
        [ ["r64/m64", "1"]                                  , "M"   , [ 0xD1 ]            , 0x48, 0, False, False,  0, "X64", False, "" ],
        [ ["r64/m64", "cl"]                                 , "M"   , [ 0xD3 ]            , 0x48, 0, False, False,  0, "X64", False, "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0xC1 ]            , 0x48, 0, False, False,  8, "X64", False, "" ],
    ]],
    [ "ROR", "", [
        [ ["r8/m8", "1"]                                    , "M"   , [ 0xD0 ]            , 0x00, 1, False, False,  0, "ANY", False, "" ],
        [ ["r8/m8", "cl"]                                   , "M"   , [ 0xD2 ]            , 0x00, 1, False, False,  0, "ANY", False, "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0xC0 ]            , 0x00, 1, False, False,  8, "ANY", False, "" ],
        [ ["r16/m16", "1"]                                  , "M"   , [ 0x66, 0xD1 ]      , 0x00, 1, False, False,  0, "ANY", False, "" ],
        [ ["r16/m16", "cl"]                                 , "M"   , [ 0x66, 0xD3 ]      , 0x00, 1, False, False,  0, "ANY", False, "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0xC1 ]      , 0x00, 1, False, False,  8, "ANY", False, "" ],
        [ ["r32/m32", "1"]                                  , "M"   , [ 0xD1 ]            , 0x00, 1, False, False,  0, "ANY", False, "" ],
        [ ["r32/m32", "cl"]                                 , "M"   , [ 0xD3 ]            , 0x00, 1, False, False,  0, "ANY", False, "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0xC1 ]            , 0x00, 1, False, False,  8, "ANY", False, "" ],
        [ ["r64/m64", "1"]                                  , "M"   , [ 0xD1 ]            , 0x48, 1, False, False,  0, "X64", False, "" ],
        [ ["r64/m64", "cl"]                                 , "M"   , [ 0xD3 ]            , 0x48, 1, False, False,  0, "X64", False, "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0xC1 ]            , 0x48, 1, False, False,  8, "X64", False, "" ],
    ]],
    [ "RET", "Return from Procedure.", [
        [ []                                                , "NONE", [ 0xC3 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
        [ ["iw"]                                            , "NONE", [ 0xC2 ]            , 0x00, 0, False, False, 16, "ANY", False, "" ],
    ]],
    [ "SAHF", "Store AH into Flags.", [
        [ ["<ah>"]                                          , "NONE", [ 0x9E ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "SAR", "", [
        [ ["r8/m8", "1"]                                    , "M"   , [ 0xD0 ]            , 0x00, 7, False, False,  0, "ANY", False, "" ],
        [ ["r8/m8", "cl"]                                   , "M"   , [ 0xD2 ]            , 0x00, 7, False, False,  0, "ANY", False, "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0xC0 ]            , 0x00, 7, False, False,  8, "ANY", False, "" ],
        [ ["r16/m16", "1"]                                  , "M"   , [ 0x66, 0xD1 ]      , 0x00, 7, False, False,  0, "ANY", False, "" ],
        [ ["r16/m16", "cl"]                                 , "M"   , [ 0x66, 0xD3 ]      , 0x00, 7, False, False,  0, "ANY", False, "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0xC1 ]      , 0x00, 7, False, False,  8, "ANY", False, "" ],
        [ ["r32/m32", "1"]                                  , "M"   , [ 0xD1 ]            , 0x00, 7, False, False,  0, "ANY", False, "" ],
        [ ["r32/m32", "cl"]                                 , "M"   , [ 0xD3 ]            , 0x00, 7, False, False,  0, "ANY", False, "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0xC1 ]            , 0x00, 7, False, False,  8, "ANY", False, "" ],
        [ ["r64/m64", "1"]                                  , "M"   , [ 0xD1 ]            , 0x48, 7, False, False,  0, "X64", False, "" ],
        [ ["r64/m64", "cl"]                                 , "M"   , [ 0xD3 ]            , 0x48, 7, False, False,  0, "X64", False, "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0xC1 ]            , 0x48, 7, False, False,  8, "X64", False, "" ],
    ]],
    [ "SHR", "", [
        [ ["r8/m8", "1"]                                    , "M"   , [ 0xD0 ]            , 0x00, 5, False, False,  0, "ANY", False, "" ],
        [ ["r8/m8", "cl"]                                   , "M"   , [ 0xD2 ]            , 0x00, 5, False, False,  0, "ANY", False, "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0xC0 ]            , 0x00, 5, False, False,  8, "ANY", False, "" ],
        [ ["r16/m16", "1"]                                  , "M"   , [ 0x66, 0xD1 ]      , 0x00, 5, False, False,  0, "ANY", False, "" ],
        [ ["r16/m16", "cl"]                                 , "M"   , [ 0x66, 0xD3 ]      , 0x00, 5, False, False,  0, "ANY", False, "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0xC1 ]      , 0x00, 5, False, False,  8, "ANY", False, "" ],
        [ ["r32/m32", "1"]                                  , "M"   , [ 0xD1 ]            , 0x00, 5, False, False,  0, "ANY", False, "" ],
        [ ["r32/m32", "cl"]                                 , "M"   , [ 0xD3 ]            , 0x00, 5, False, False,  0, "ANY", False, "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0xC1 ]            , 0x00, 5, False, False,  8, "ANY", False, "" ],
        [ ["r64/m64", "1"]                                  , "M"   , [ 0xD1 ]            , 0x48, 5, False, False,  0, "X64", False, "" ],
        [ ["r64/m64", "cl"]                                 , "M"   , [ 0xD3 ]            , 0x48, 5, False, False,  0, "X64", False, "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0xC1 ]            , 0x48, 5, False, False,  8, "X64", False, "" ],
    ]],
    [ "SBB", "Integer Subtraction with Borrow", [
        [ ["al", "ib"]                                      , "I"   , [ 0x1C ]            , 0x00, 0, False, False,  8, "ANY", True , "" ],
        [ ["ax", "iw"]                                      , "I"   , [ 0x66, 0x1D ]      , 0x00, 0, False, False, 16, "ANY", True , "" ],
        [ ["eax", "id"]                                     , "I"   , [ 0x1D ]            , 0x00, 0, False, False, 32, "ANY", True , "" ],
        [ ["rax", "id"]                                     , "I"   , [ 0x1D ]            , 0x48, 0, False, False, 32, "X64", True , "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0x80 ]            , 0x00, 3, False, False,  8, "ANY", True , "" ],
        [ ["r16/m16", "iw"]                                 , "MI"  , [ 0x66, 0x81 ]      , 0x00, 3, False, False, 16, "ANY", True , "" ],
        [ ["r32/m32", "id"]                                 , "MI"  , [ 0x81 ]            , 0x00, 3, False, False, 32, "ANY", True , "" ],
        [ ["r64/m64", "id"]                                 , "MI"  , [ 0x81 ]            , 0x48, 3, False, False, 32, "X64", True , "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0x83 ]      , 0x00, 3, False, False,  8, "ANY", True , "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x00, 3, False, False,  8, "ANY", True , "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x48, 3, False, False,  8, "X64", True , "" ],
        [ ["r8/m8", "r8"]                                   , "MR"  , [ 0x18 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x19 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x19 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x19 ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
        [ ["r8", "r8/m8"]                                   , "RM"  , [ 0x1A ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x1B ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x1B ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x1B ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
    ]],
    [ "SCASB", "", [
        [ ["<al>", "<es:zdi>"]                              , "NONE", [ 0xAE ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "SCASW", "", [
        [ ["<ax>", "<es:zdi>"]                              , "NONE", [ 0x66, 0xAF ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "SCASD", "", [
        [ ["<eax>", "<es:zdi>"]                             , "NONE", [ 0xAF ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "SCASQ", "", [
        [ ["<rax>", "<es:zdi>"]                             , "NONE", [ 0xAF ]            , 0x48, 0, False, False,  0, "X64", False, "" ],
    ]],
    [ "SETO", "", [
        [ ["r8/m8"]                                         , "M"   , [ 0x0F, 0x90 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
    ]],
    [ "SETNO", "", [
        [ ["r8/m8"]                                         , "M"   , [ 0x0F, 0x91 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
    ]],
    [ "SETS", "", [
        [ ["r8/m8"]                                         , "M"   , [ 0x0F, 0x98 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
    ]],
    [ "SETNS", "", [
        [ ["r8/m8"]                                         , "M"   , [ 0x0F, 0x99 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
    ]],
    [ "SHLD", "Double Precision Shift Left.", [
        [ ["r16/m16", "r16", "ib"]                          , "MRI" , [ 0x66, 0x0F, 0xA4 ], 0x00, 0, False, True ,  8, "ANY", False, "" ],
        [ ["r16/m16", "r16", "cl"]                          , "MR"  , [ 0x66, 0x0F, 0xA5 ], 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32/m32", "r32", "ib"]                          , "MRI" , [ 0x0F, 0xA4 ]      , 0x00, 0, False, True ,  8, "ANY", False, "" ],
        [ ["r32/m32", "r32", "cl"]                          , "MR"  , [ 0x0F, 0xA5 ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64/m64", "r64", "ib"]                          , "MRI" , [ 0x0F, 0xA4 ]      , 0x48, 0, False, True ,  8, "X64", False, "" ],
        [ ["r64/m64", "r64", "cl"]                          , "MR"  , [ 0x0F, 0xA5 ]      , 0x48, 0, False, True ,  0, "X64", False, "" ],
    ]],
    [ "SHRD", "Double Precision Shift Right", [
        [ ["r16/m16", "r16", "ib"]                          , "MRI" , [ 0x66, 0x0F, 0xAC ], 0x00, 0, False, True ,  8, "ANY", False, "" ],
        [ ["r16/m16", "r16", "cl"]                          , "MR"  , [ 0x66, 0x0F, 0xAD ], 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r32/m32", "r32", "ib"]                          , "MRI" , [ 0x0F, 0xAC ]      , 0x00, 0, False, True ,  8, "ANY", False, "" ],
        [ ["r32/m32", "r32", "cl"]                          , "MR"  , [ 0x0F, 0xAD ]      , 0x00, 0, False, True ,  0, "ANY", False, "" ],
        [ ["r64/m64", "r64", "ib"]                          , "MRI" , [ 0x0F, 0xAC ]      , 0x48, 0, False, True ,  8, "X64", False, "" ],
        [ ["r64/m64", "r64", "cl"]                          , "MR"  , [ 0x0F, 0xAD ]      , 0x48, 0, False, True ,  0, "X64", False, "" ],
    ]],
    [ "STAC", "Set AC Flag in EFLAGS Register", [
        [ []                                                , "NONE", [ 0x0F, 0x01, 0xCB ], 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "STC", "Set Carry Flag", [
        [ []                                                , "NONE", [ 0xF9 ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "STD", "Set Direction Flag.", [
        [ []                                                , "NONE", [ 0xFD ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "STI", "Set Interrupt Flag.", [
        [ []                                                , "NONE", [ 0xFB ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "STOSB", "", [
        [ ["<es:zdi>", "<al>"]                              , "NONE", [ 0xAA ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "STOSW", "", [
        [ ["<es:zdi>", "<ax>"]                              , "NONE", [ 0x66, 0xAB ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "STOSD", "", [
        [ ["<es:zdi>", "<eax>"]                             , "NONE", [ 0xAB ]            , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "STOSQ", "", [
        [ ["<es:zdi>", "<rax>"]                             , "NONE", [ 0xAB ]            , 0x48, 0, False, False,  0, "X64", False, "" ],
    ]],
    [ "SUB", "Subtract", [
        [ ["al", "ib"]                                      , "I"   , [ 0x2C ]            , 0x00, 0, False, False,  8, "ANY", True , "" ],
        [ ["ax", "iw"]                                      , "I"   , [ 0x66, 0x2D ]      , 0x00, 0, False, False, 16, "ANY", True , "" ],
        [ ["eax", "id"]                                     , "I"   , [ 0x2D ]            , 0x00, 0, False, False, 32, "ANY", True , "" ],
        [ ["rax", "id"]                                     , "I"   , [ 0x2D ]            , 0x48, 0, False, False, 32, "X64", True , "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0x80 ]            , 0x00, 5, False, False,  8, "ANY", True , "" ],
        [ ["r16/m16", "iw"]                                 , "MI"  , [ 0x66, 0x81 ]      , 0x00, 5, False, False, 16, "ANY", True , "" ],
        [ ["r32/m32", "id"]                                 , "MI"  , [ 0x81 ]            , 0x00, 5, False, False, 32, "ANY", True , "" ],
        [ ["r64/m64", "id"]                                 , "MI"  , [ 0x81 ]            , 0x48, 5, False, False, 32, "X64", True , "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0x83 ]      , 0x00, 5, False, False,  8, "ANY", True , "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x00, 5, False, False,  8, "ANY", True , "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x48, 5, False, False,  8, "X64", True , "" ],
        [ ["r8/m8", "r8"]                                   , "MR"  , [ 0x28 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x29 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x29 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x29 ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
        [ ["r8", "r8/m8"]                                   , "RM"  , [ 0x2A ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x2B ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x2B ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x2B ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
    ]],
    [ "SWAPGS", "Swap GS Base Register", [
        [ []                                                , "NONE", [ 0x0F, 0x01, 0xF8 ], 0x00, 0, False, False,  0, "X64", False, "" ],
    ]],
    [ "TEST", "Logical Compare", [
        [ ["al", "ib"]                                      , "I"   , [ 0xA8 ]            , 0x00, 0, False, False,  8, "ANY", True , "" ],
        [ ["ax", "iw"]                                      , "I"   , [ 0x66, 0xA9 ]      , 0x00, 0, False, False, 16, "ANY", True , "" ],
        [ ["eax", "id"]                                     , "I"   , [ 0xA9 ]            , 0x00, 0, False, False, 32, "ANY", True , "" ],
        [ ["rax", "id"]                                     , "I"   , [ 0xA9 ]            , 0x48, 0, False, False, 32, "X64", True , "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0xF6 ]            , 0x00, 0, False, False,  8, "ANY", True , "" ],
        [ ["r16/m16", "iw"]                                 , "MI"  , [ 0x66, 0xF7 ]      , 0x00, 0, False, False, 16, "ANY", True , "" ],
        [ ["r32/m32", "id"]                                 , "MI"  , [ 0xF7 ]            , 0x00, 0, False, False, 32, "ANY", True , "" ],
        [ ["r64/m64", "id"]                                 , "MI"  , [ 0xF7 ]            , 0x48, 0, False, False, 32, "X64", True , "" ],
        [ ["r8/m8", "r8"]                                   , "MR"  , [ 0x84 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x85 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x85 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x85 ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
    ]],
    [ "UD2", "Undefined Instruction.", [
        [ []                                                , "NONE", [ 0x0F, 0x0B ]      , 0x00, 0, False, False,  0, "ANY", False, "" ],
    ]],
    [ "XADD", "Exchange and Add", [
        [ ["r8/m8", "r8"]                                   , "MR"  , [ 0x0F, 0xC0 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x0F, 0xC1 ], 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x0F, 0xC1 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x0F, 0xC1 ]      , 0x48, 0, False, True ,  0, "X64", True , "" ],
    ]],
    [ "XCHG", "Exchange Register/Memory with Register", [
        [ ["ax", "r16"]                                     , "O"   , [ 0x66, 0x90 ]      , 0x00, 0, True , False,  0, "ANY", True , "" ],
        [ ["eax", "r32"]                                    , "O"   , [ 0x90 ]            , 0x00, 0, True , False,  0, "ANY", True , "" ],
        [ ["rax", "r64"]                                    , "O"   , [ 0x90 ]            , 0x48, 0, True , False,  0, "X64", True , "" ],
        [ ["r16", "ax"]                                     , "O"   , [ 0x66, 0x90 ]      , 0x00, 0, True , False,  0, "ANY", True , "" ],
        [ ["r32", "eax"]                                    , "O"   , [ 0x90 ]            , 0x00, 0, True , False,  0, "ANY", True , "" ],
        [ ["r64", "rax"]                                    , "O"   , [ 0x90 ]            , 0x48, 0, True , False,  0, "X64", True , "" ],
        [ ["r8/m8", "r8"]                                   , "MR"  , [ 0x86 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x87 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x87 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x87 ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
        [ ["r8", "r8/m8"]                                   , "RM"  , [ 0x86 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x87 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x87 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x87 ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
    ]],
    [ "XOR", "Logical Exclusive OR", [
        [ ["al", "ib"]                                      , "I"   , [ 0x34 ]            , 0x00, 0, False, False,  8, "ANY", True , "" ],
        [ ["ax", "iw"]                                      , "I"   , [ 0x66, 0x35 ]      , 0x00, 0, False, False, 16, "ANY", True , "" ],
        [ ["eax", "id"]                                     , "I"   , [ 0x35 ]            , 0x00, 0, False, False, 32, "ANY", True , "" ],
        [ ["rax", "id"]                                     , "I"   , [ 0x35 ]            , 0x48, 0, False, False, 32, "X64", True , "" ],
        [ ["r8/m8", "ib"]                                   , "MI"  , [ 0x80 ]            , 0x00, 6, False, False,  8, "ANY", True , "" ],
        [ ["r16/m16", "iw"]                                 , "MI"  , [ 0x66, 0x81 ]      , 0x00, 6, False, False, 16, "ANY", True , "" ],
        [ ["r32/m32", "id"]                                 , "MI"  , [ 0x81 ]            , 0x00, 6, False, False, 32, "ANY", True , "" ],
        [ ["r64/m64", "id"]                                 , "MI"  , [ 0x81 ]            , 0x48, 6, False, False, 32, "X64", True , "" ],
        [ ["r16/m16", "ib"]                                 , "MI"  , [ 0x66, 0x83 ]      , 0x00, 6, False, False,  8, "ANY", True , "" ],
        [ ["r32/m32", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x00, 6, False, False,  8, "ANY", True , "" ],
        [ ["r64/m64", "ib"]                                 , "MI"  , [ 0x83 ]            , 0x48, 6, False, False,  8, "X64", True , "" ],
        [ ["r8/m8", "r8"]                                   , "MR"  , [ 0x30 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16/m16", "r16"]                                , "MR"  , [ 0x66, 0x31 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32/m32", "r32"]                                , "MR"  , [ 0x31 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64/m64", "r64"]                                , "MR"  , [ 0x31 ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
        [ ["r8", "r8/m8"]                                   , "RM"  , [ 0x32 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r16", "r16/m16"]                                , "RM"  , [ 0x66, 0x33 ]      , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r32", "r32/m32"]                                , "RM"  , [ 0x33 ]            , 0x00, 0, False, True ,  0, "ANY", True , "" ],
        [ ["r64", "r64/m64"]                                , "RM"  , [ 0x33 ]            , 0x48, 0, False, True ,  0, "X64", True , "" ],
    ]],
]
